#!/bin/sh
while :
do
 	echo 1.添加记录，2.显示数据，3.更新学生表，4.输出成绩统计, 5.退出
	read select
	case	"$select" in
		1 )
			./addrecord
			echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
			;;
		2 )
			./showInfo
			echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
			;;
		3 )
			./update
			echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
			;;
		4 )
			./countScore
			echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
			;;
		5 )
			exit 0
			;;
		* )
			echo 输入错误，请重新输入
			read select
	esac
done
